// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigModel() {
  return window['go']['main']['GUI']['GetConfigModel']();
}

export function AppVersion() {
  return window['go']['main']['GUI']['AppVersion']();
}

export function GetUpdateStatus() {
  return window['go']['main']['GUI']['GetUpdateStatus']();
}

export function CheckUpdates() {
  return window['go']['main']['GUI']['CheckUpdates']();
}

export function GetSchedulerStatus() {
  return window['go']['main']['GUI']['GetSchedulerStatus']();
}

export function GetScreens() {
  return window['go']['main']['GUI']['GetScreens']();
}

export function GetSnapshot() {
  return window['go']['main']['GUI']['GetSnapshot']();
}

export function InstallScheduler() {
  return window['go']['main']['GUI']['InstallScheduler']();
}

export function IsCheckProcessRunning() {
  return window['go']['main']['GUI']['IsCheckProcessRunning']();
}

export function KillCMD() {
  return window['go']['main']['GUI']['KillCMD']();
}

export function KillNode() {
  return window['go']['main']['GUI']['KillNode']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['GUI']['OpenFolder'](arg1);
}

export function RemoveScheduler() {
  return window['go']['main']['GUI']['RemoveScheduler']();
}

export function Restart(arg1) {
  return window['go']['main']['GUI']['Restart'](arg1);
}

export function RestartAll() {
  return window['go']['main']['GUI']['RestartAll']();
}

export function RestartAutoManual() {
  return window['go']['main']['GUI']['RestartAutoManual']();
}

export function SaveConfigModel(arg1) {
  return window['go']['main']['GUI']['SaveConfigModel'](arg1);
}

export function SetDisabled(arg1, arg2) {
  return window['go']['main']['GUI']['SetDisabled'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['main']['GUI']['Start'](arg1);
}

export function StartCheckProcess() {
  return window['go']['main']['GUI']['StartCheckProcess']();
}

export function Stop(arg1) {
  return window['go']['main']['GUI']['Stop'](arg1);
}

export function StopAll() {
  return window['go']['main']['GUI']['StopAll']();
}

export function StopCheckProcess() {
  return window['go']['main']['GUI']['StopCheckProcess']();
}
