// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {display} from '../models';
import {app} from '../models';

export function GetConfigModel():Promise<config.ConfigDTO>;

export function GetSchedulerStatus():Promise<main.TaskStatus>;

export function GetScreens():Promise<Array<display.Screen>>;

export function GetSnapshot():Promise<app.DisplaySnapshot>;

export function InstallScheduler():Promise<void>;

export function IsCheckProcessRunning():Promise<boolean>;

export function KillCMD():Promise<void>;

export function KillNode():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveScheduler():Promise<void>;

export function Restart(arg1:string):Promise<void>;

export function RestartAll():Promise<void>;

export function RestartAutoManual():Promise<void>;

export function SaveConfigModel(arg1:config.ConfigDTO):Promise<void>;

export function SetDisabled(arg1:string,arg2:boolean):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function StartCheckProcess():Promise<boolean>;

export function Stop(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopCheckProcess():Promise<boolean>;
